spring:
  application:
    name: psm-user-service

  config:
    import: configserver:http://localhost:8888/
  
  datasource:
    url: jdbc:mysql://localhost:3306/psm_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       
    hibernate:
      ddl-auto: update

